title: "Nils Johansson Blog"
author: "Nils (Sudesh) Johansson"
description: "Field Service Engineer @ Instron | Marine & Industrial Specialist | Advocate for Vietnam & Southeast Asia"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
theme: minima
plugins:
  - jekyll-feed
